name: Export Framer Sites to HTML

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  export-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Axios
        run: npm install axios

      - name: Export Main Framer Site
        env:
          FRAMER_URL: 'https://semat.framer.website'
        run: |
          mkdir -p exported_site
          node <<'EOF'
          const axios = require('axios');
          const fs = require('fs').promises;
          const path = require('path');

          const exportSite = async (url, outputPath) => {
            try {
              const response = await axios.post('https://nocodexport.com/tools/framer-to-html', { url }, { responseType: 'text' });
              await fs.writeFile(outputPath, response.data);
              console.log(`Site exported successfully: ${url}`);
            } catch (error) {
              console.error(`Error exporting site (${url}):`, error.message);
              process.exit(1);
            }
          };

          (async () => {
            const urls = ['https://semat.framer.website', 'https://semat.framer.website/ar'];
            for (const url of urls) {
              const outputPath = url.endsWith('/ar') ? path.join(__dirname, 'exported_site', 'ar', 'index.html') : path.join(__dirname, 'exported_site', 'index.html');
              await exportSite(url, outputPath);
            }
          })();
          EOF

      - name: Commit and Push Changes
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          cd exported_site
          git init
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Automated update of exported Framer sites"
          git remote add origin https://github.com/${{ github.repository }}.git
          git push -u origin HEAD:main --force
