name: Maintain Semat Agency Site

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */8 * * *'  # Runs every 8 hours
  workflow_dispatch:

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y python3 curl

      - name: Post-Process HTML for Arabic (Root)
        run: |
          # Ensure Arabic root files have correct dir, lang, SEO tags, styles, and schema
          find . -type f -name "*.html" -not -path "./en/*" -exec sed -i \
            -e 's/<html/<html dir="rtl" lang="ar"/' \
            -e '/<head>/a <link rel="canonical" href="https://semat.agency/" />' \
            -e '/<head>/a <link rel="alternate" hreflang="ar-SA" href="https://semat.agency/" />' \
            -e '/<head>/a <link rel="alternate" hreflang="ar" href="https://semat.agency/" />' \
            -e '/<head>/a <link rel="alternate" hreflang="en" href="https://semat.agency/en" />' \
            -e '/<head>/a <link rel="alternate" hreflang="x-default" href="https://semat.agency/" />' \
            -e '/<head>/a <style>body { direction: rtl; text-align: right; overflow-x: hidden; margin: 0; padding: 0; } #__framer-badge-container, .framer-nm3c8g { display: none !important; } [data-framer-component] { direction: rtl !important; } .framer-text.framer-image { border-radius: 20px !important; max-height: 500px !important; object-fit: cover !important; }<\/style>' \
            -e '/<head>/a <script type="application/ld+json">{"@context":"https://schema.org","@type":"LocalBusiness","name":"Semat Agency","description":"Semat Agency provides IT solutions, digital marketing, and custom software development for businesses in Saudi Arabia.","url":"https://semat.agency/index.html","address":{"@type":"PostalAddress","streetAddress":"123 Business Street","addressLocality":"Riyadh","addressRegion":"Riyadh Province","addressCountry":"SA","postalCode":"12345"},"telephone":"+966-50-361-7701","openingHours":"Mo-Fr 09:00-17:00","geo":{"@type":"GeoCoordinates","latitude":"24.7136","longitude":"46.6753"},"sameAs":["https://semat.agency/servieces.html","https://semat.agency/solutions.html","https://semat.agency/contact-us.html"]}<\/script>' \
            {} \;

      - name: Post-Process HTML for English (/en)
        run: |
          # Ensure English files have correct dir, lang, SEO tags, styles, and schema
          find ./en -type f -name "*.html" -exec sed -i \
            -e 's/<html/<html dir="ltr" lang="en"/' \
            -e '/<head>/a <link rel="canonical" href="https://semat.agency/en" />' \
            -e '/<head>/a <link rel="alternate" hreflang="ar-SA" href="https://semat.agency/" />' \
            -e '/<head>/a <link rel="alternate" hreflang="ar" href="https://semat.agency/" />' \
            -e '/<head>/a <link rel="alternate" hreflang="en" href="https://semat.agency/en" />' \
            -e '/<head>/a <link rel="alternate" hreflang="x-default" href="https://semat.agency/" />' \
            -e '/<head>/a <style>body { direction: ltr; text-align: left; overflow-x: hidden; margin: 0; padding: 0; } #__framer-badge-container, .framer-nm3c8g { display: none !important; } [data-framer-component] { direction: ltr !important; } .framer-text.framer-image { border-radius: 20px !important; max-height: 500px !important; object-fit: cover !important; }<\/style>' \
            -e '/<head>/a <script type="application/ld+json">{"@context":"https://schema.org","@type":"LocalBusiness","name":"Semat Agency","description":"Semat Agency provides IT solutions, digital marketing, and custom software development for businesses in Saudi Arabia.","url":"https://semat.agency/index.html","address":{"@type":"PostalAddress","streetAddress":"123 Business Street","addressLocality":"Riyadh","addressRegion":"Riyadh Province","addressCountry":"SA","postalCode":"12345"},"telephone":"+966-50-361-7701","openingHours":"Mo-Fr 09:00-17:00","geo":{"@type":"GeoCoordinates","latitude":"24.7136","longitude":"46.6753"},"sameAs":["https://semat.agency/servieces.html","https://semat.agency/solutions.html","https://semat.agency/contact-us.html"]}<\/script>' \
            {} \;

      - name: Generate Sitemaps, Robots, and RSS
        run: |
          # Sitemap for root (Arabic)
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          find . -type f -name "*.html" -not -path "./en/*" | while read -r file; do
            url="https://semat.agency/${file#./}"
            lastmod=$(date -u -d "now" +%Y-%m-%dT%H:%M:%SZ)
            priority=$(if [[ "$file" == "./index.html" ]]; then echo "1.0"; else echo "0.8"; fi)
            echo "  <url><loc>$url</loc><lastmod>$lastmod</lastmod><changefreq>daily</changefreq><priority>$priority</priority></url>" >> sitemap.xml
          done
          echo '</urlset>' >> sitemap.xml

          # Sitemap for /en (English)
          echo '<?xml version="1.0" encoding="UTF-8"?>' > en/sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> en/sitemap.xml
          find ./en -type f -name "*.html" | while read -r file; do
            url="https://semat.agency/${file#./}"
            lastmod=$(date -u -d "now" +%Y-%m-%dT%H:%M:%SZ)
            priority=$(if [[ "$file" == "./en/index.html" ]]; then echo "1.0"; else echo "0.8"; fi)
            echo "  <url><loc>$url</loc><lastmod>$lastmod</lastmod><changefreq>daily</changefreq><priority>$priority</priority></url>" >> en/sitemap.xml
          done
          echo '</urlset>' >> sitemap.xml

          # Robots.txt
          echo "User-agent: *" > robots.txt
          echo "Allow: /" >> robots.txt
          echo "Allow: /en/" >> robots.txt
          echo "Disallow: /*?*" >> robots.txt
          echo "Disallow: /index.html" >> robots.txt
          echo "Sitemap: https://semat.agency/sitemap.xml" >> robots.txt
          echo "Sitemap: https://semat.agency/en/sitemap.xml" >> robots.txt

          # Verify robots.txt
          if [ -f robots.txt ]; then
            echo "robots.txt generated:"
            cat robots.txt
          else
            echo "Failed to generate robots.txt" >&2
            exit 1
          fi

          # RSS feed
          echo '<?xml version="1.0" encoding="UTF-8"?>' > rss.xml
          echo '<rss version="2.0"><channel>' >> rss.xml
          echo "<title>Semat Agency Updates</title><link>https://semat.agency</link><description>Latest updates from Semat Agency</description>" >> rss.xml
          find . -type f -name "*.html" -not -path "./en/*" | while read -r file; do
            url="https://semat.agency/${file#./}"
            title=$(basename "$file" .html | tr '-' ' ' | awk '{for(i=1;i<=NF;i++){$i=toupper(substr($i,1,1)) substr($i,2)}}1')
            echo "<item><title>Arabic: $title</title><link>$url</link><pubDate>$(date -u -R)</pubDate><description>Updated Arabic page</description></item>" >> rss.xml
          done
          find ./en -type f -name "*.html" | while read -r file; do
            url="https://semat.agency/${file#./}"
            title=$(basename "$file" .html | tr '-' ' ' | awk '{for(i=1;i<=NF;i++){$i=toupper(substr($i,1,1)) substr($i,2)}}1')
            echo "<item><title>English: $title</title><link>$url</link><pubDate>$(date -u -R)</pubDate><description>Updated English page</description></item>" >> rss.xml
          done
          echo '</channel></rss>' >> rss.xml

      - name: Commit and Push Changes
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated update: Standalone semat.agency with schema"
            git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git HEAD:main
          fi

      - name: Verify Deployment
        run: |
          echo "Verifying deployment..."
          sleep 10  # Adjust based on deployment time
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://semat.agency/)
          if [ "$STATUS" -eq 200 ]; then
            echo "Root (Arabic) accessible (HTTP $STATUS)"
          else
            echo "Root failed (HTTP $STATUS)" >&2
            exit 1
          fi
          STATUS_EN=$(curl -s -o /dev/null -w "%{http_code}" https://semat.agency/en)
          if [ "$STATUS_EN" -eq 200 ]; then
            echo "English accessible (HTTP $STATUS_EN)"
          else
            echo "English failed (HTTP $STATUS_EN)" >&2
            exit 1
          fi
          STATUS_ROBOTS=$(curl -s -o /dev/null -w "%{http_code}" https://semat.agency/robots.txt)
          if [ "$STATUS_ROBOTS" -eq 200 ]; then
            echo "robots.txt accessible (HTTP $STATUS_ROBOTS)"
            curl -s https://semat.agency/robots.txt
          else
            echo "robots.txt failed (HTTP $STATUS_ROBOTS)" >&2
            exit 1
          fi
