name: Maintain Semat Agency Site

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */8 * * *'  # Runs every 8 hours
  workflow_dispatch:

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y python3 curl httrack rsync

      - name: Export Arabic Framer Site (Main Site)
        run: |
          echo "Downloading Arabic site..."
          httrack "https://semat.framer.website/ar" -O ./main_site --mirror --keep-alive --depth=2 --clean
          if [ -d "./main_site/semat.framer.website/ar" ]; then
            rsync -a ./main_site/semat.framer.website/ar/ ./
          fi
          rm -rf ./main_site

      - name: Export English Framer Site
        run: |
          echo "Downloading English site..."
          httrack "https://semat.framer.website/" -O ./en_site --mirror --keep-alive --depth=2 --clean
          mkdir -p ./en
          if [ -d "./en_site/semat.framer.website" ]; then
            rsync -a --exclude 'ar' ./en_site/semat.framer.website/ ./en/
          fi
          rm -rf ./en_site

      - name: Post-Process HTML for Arabic (Root)
        run: |
          find . -type f -name "*.html" -not -path "./en/*" | while read -r file; do
            # Remove all HTML comments and specific Framer/HTTrack comments
            sed -i \
              -e 's/<!--.*-->//g' \
              -e '/<!-- Mirrored from semat\.framer\.website\/[a-z\/]* by HTTrack Website Copier\/3\.x \[XR&CO'\''2014\], .* GMT -->/d' \
              -e '/<!-- ✨ Built with Framer • https:\/\/www.framer.com\/ -->/d' \
              -e 's/<html/<html dir="rtl" lang="ar"/' \
              -e '/<base /d' \
              -e '/<head>/a <link rel="canonical" href="https://www.semat.agency/" />' \
              -e '/<head>/a <link rel="alternate" hreflang="ar-SA" href="https://www.semat.agency/" />' \
              -e '/<head>/a <link rel="alternate" hreflang="ar" href="https://www.semat.agency/" />' \
              -e '/<head>/a <link rel="alternate" hreflang="en" href="https://www.semat.agency/en" />' \
              -e '/<head>/a <link rel="alternate" hreflang="x-default" href="https://www.semat.agency/" />' \
              -e '/<head>/a <style> .framer-NdJds.framer-138s38m{direction:rtl;text-align: right} body { direction: rtl; text-align: right; overflow-x: hidden; margin: 0; padding: 0; } #__framer-badge-container, .framer-nm3c8g { display: none !important; } .framer-text.framer-image { border-radius: 20px !important; max-height: 500px !important; object-fit: cover !important; }<\/style>' \
              -e '/<head>/a <script type="application/ld+json">{"@context":"https://schema.org","@type":"LocalBusiness","name":"Semat Agency","description":"Semat Agency provides IT solutions, digital marketing, and custom software development for businesses in Saudi Arabia.","url":"https://www.semat.agency/en","address":{"@type":"PostalAddress","streetAddress":"123 Business Street","addressLocality":"Riyadh","addressRegion":"Riyadh Province","addressCountry":"SA","postalCode":"12345"},"telephone":"+966-50-361-7701","openingHours":"Mo-Fr 09:00-17:00","geo":{"@type":"GeoCoordinates","latitude":"24.7136","longitude":"46.6753"},"sameAs":["https://www.semat.agency/en/services.html","https://www.semat.agency/en/solutions.html","https://www.semat.agency/en/contact-us.html"]}<\/script>' \
              "$file"
          done

      - name: Post-Process HTML for English (/en)
        run: |
          find ./en -type f -name "*.html" | while read -r file; do
            # Remove all HTML comments and specific Framer/HTTrack comments
            sed -i \
              -e 's/<!--.*-->//g' \
              -e '/<!-- Mirrored from semat\.framer\.website\/[a-z\/]* by HTTrack Website Copier\/3\.x \[XR&CO'\''2014\], .* GMT -->/d' \
              -e '/<!-- ✨ Built with Framer • https:\/\/www.framer.com\/ -->/d' \
              -e 's/<html/<html dir="ltr" lang="en"/' \
              -e '/<base /d' \
              -e '/<head>/a <link rel="canonical" href="https://www.semat.agency/en" />' \
              -e '/<head>/a <link rel="alternate" hreflang="ar-SA" href="https://www.semat.agency/" />' \
              -e '/<head>/a <link rel="alternate" hreflang="ar" href="https://www.semat.agency/" />' \
              -e '/<head>/a <link rel="alternate" hreflang="en" href="https://www.semat.agency/en" />' \
              -e '/<head>/a <link rel="alternate" hreflang="x-default" href="https://www.semat.agency/en" />' \
              -e '/<head>/a <style>body { direction: ltr; text-align: left; overflow-x: hidden; margin: 0; padding: 0; } #__framer-badge-container, .framer-nm3c8g { display: none !important; } .framer-text.framer-image { border-radius: 20px !important; max-height: 500px !important; object-fit: cover !important; }<\/style>' \
              -e '/<head>/a <script type="application/ld+json">{"@context":"https://schema.org","@type":"LocalBusiness","name":"Semat Agency","description":"Semat Agency provides IT solutions, digital marketing, and custom software development for businesses in Saudi Arabia.","url":"https://www.semat.agency/","address":{"@type":"PostalAddress","streetAddress":"123 Business Street","addressLocality":"Riyadh","addressRegion":"Riyadh Province","addressCountry":"SA","postalCode":"12345"},"telephone":"+966-50-361-7701","openingHours":"Mo-Fr 09:00-17:00","geo":{"@type":"GeoCoordinates","latitude":"24.7136","longitude":"46.6753"},"sameAs":["https://www.semat.agency/services.html","https://www.semat.agency/solutions.html","https://www.semat.agency/contact-us.html"]}<\/script>' \
              "$file"
          done

      - name: Generate Sitemaps, Robots, and RSS
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          find . -type f -name "*.html" -not -path "./en/*" | while read -r file; do
            url="https://www.semat.agency/${file#./}"
            lastmod=$(date -u -d "now" +%Y-%m-%dT%H:%M:%SZ)
            priority=$(if [[ "$file" == "./index.html" ]]; then echo "1.0"; else echo "0.8"; fi)
            echo "  <url><loc>$url</loc><lastmod>$lastmod</lastmod><changefreq>daily</changefreq><priority>$priority</priority></url>" >> sitemap.xml
          done
          echo '</urlset>' >> sitemap.xml

          echo '<?xml version="1.0" encoding="UTF-8"?>' > en/sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> en/sitemap.xml
          find ./en -type f -name "*.html" | while read -r file; do
            url="https://www.semat.agency/${file#./}"
            lastmod=$(date -u -d "now" +%Y-%m-%dT%H:%M:%SZ)
            priority=$(if [[ "$file" == "./en/index.html" ]]; then echo "1.0"; else echo "0.8"; fi)
            echo "  <url><loc>$url</loc><lastmod>$lastmod</lastmod><changefreq>daily</changefreq><priority>$priority</priority></url>" >> en/sitemap.xml
          done
          echo '</urlset>' >> en/sitemap.xml

          echo "User-agent: *" > robots.txt
          echo "Allow: /" >> robots.txt
          echo "Allow: /en/" >> robots.txt
          echo "Disallow: /*?*" >> robots.txt
          echo "Disallow: /index.html" >> robots.txt
          echo "Sitemap: https://www.semat.agency/sitemap.xml" >> robots.txt
          echo "Sitemap: https://www.semat.agency/en/sitemap.xml" >> robots.txt
          if [ -f robots.txt ]; then
            echo "robots.txt generated:"
            cat robots.txt
          else
            echo "Failed to generate robots.txt" >&2
            exit 1
          fi

          echo '<?xml version="1.0" encoding="UTF-8"?>' > rss.xml
          echo '<rss version="2.0"><channel>' >> rss.xml
          echo "<title>Maintain Semat Agency Site</title><link>https://www.semat.agency</link><description>Automated updates for Semat Agency site maintenance</description>" >> rss.xml
          find . -type f -name "*.html" -not -path "./en/*" | while read -r file; do
            url="https://www.semat.agency/${file#./}"
            echo "<item><title>Arabic Page Update: ${file#./}</title><link>$url</link><pubDate>$(date -u -R)</pubDate><description>Updated Arabic page at ${file#./}</description></item>" >> rss.xml
          done
          find ./en -type f -name "*.html" | while read -r file; do
            url="https://www.semat.agency/${file#./}"
            echo "<item><title>English Page Update: ${file#./}</title><link>$url</link><pubDate>$(date -u -R)</pubDate><description>Updated English page at ${file#./}</description></item>" >> rss.xml
          done
          echo '</channel></rss>' >> rss.xml

      - name: Commit and Push Changes
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated update: Cloned and processed Semat Agency site"
            git fetch origin
            git pull origin main
            git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git HEAD:main
          fi
