name: Export Framer Sites to HTML

on:
  schedule:
    - cron: '*/2 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  export-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install HTTrack
        run: sudo apt-get install -y httrack

      - name: Export Main Framer Site
        run: |
          httrack "https://semat.framer.website/" -O ./main_site --mirror --keep-alive --depth=2 --clean
          # Move the downloaded content to the root directory
          mv ./main_site/semat.framer.website/* ./
          rm -rf ./main_site

      - name: Export Arabic Framer Site
        run: |
          httrack "https://semat.framer.website/ar" -O ./ar_site --mirror --keep-alive --depth=2 --clean
          # Move the downloaded content to the /ar directory
          mkdir -p ./ar
          mv ./ar_site/semat.framer.website/ar/* ./ar/
          rm -rf ./ar_site

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated update of exported Framer sites"
            git push origin HEAD:main
