name: Export Framer Sites to HTML

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  export-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Export Framer Sites
        run: |
          # Create directories for the exported sites
          mkdir -p exported_site/ar

          # Define the base URL and output directories
          BASE_URL="https://semat.framer.website"
          OUTPUT_DIR="exported_site"

          # Function to download a site using wget
          download_site() {
            local url=$1
            local output_path=$2

            wget --mirror --convert-links --adjust-extension --page-requisites --no-parent --directory-prefix="$output_path" "$url"
          }

          # Download the main site
          download_site "$BASE_URL" "$OUTPUT_DIR"

          # Download the Arabic version of the site
          download_site "$BASE_URL/ar" "$OUTPUT_DIR/ar"

      - name: Commit and Push Changes
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add exported_site
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated update of exported Framer sites"
            git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git HEAD:main
          fi
