name: Export Framer Sites to HTML

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  export-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install axios

      - name: Export Framer Sites
        run: |
          mkdir -p exported_site/ar
          node <<'EOF'
          const axios = require('axios');
          const fs = require('fs').promises;
          const path = require('path');

          const exportSite = async (url, outputPath) => {
            try {
              const response = await axios.post('https://nocodexport.com/tools/framer-to-html', { url }, { responseType: 'text' });
              await fs.writeFile(outputPath, response.data);
              console.log(`Site exported successfully: ${url}`);
            } catch (error) {
              console.error(`Error exporting site (${url}):`, error.message);
              process.exit(1);
            }
          };

          (async () => {
            const sites = [
              { url: 'https://semat.framer.website', outputPath: path.join(process.cwd(), 'exported_site', 'index.html') },
              { url: 'https://semat.framer.website/ar', outputPath: path.join(process.cwd(), 'exported_site', 'ar', 'index.html') }
            ];

            for (const site of sites) {
              await exportSite(site.url, site.outputPath);
            }
          })();
          EOF

      - name: Commit and Push Changes
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add exported_site
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated update of exported Framer sites"
            git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git HEAD:main
          fi
