name: Export Framer Sites to HTML

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/40 * * * *'  # Runs every 40 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  export-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install HTTrack
        run: sudo apt-get install -y httrack

      - name: Export Arabic Framer Site (Now the Main Site)
        run: |
          echo "Downloading Arabic site as main..."
          httrack "https://semat.framer.website/ar" -O ./ar_site --mirror --keep-alive --depth=2 --clean
          # Sync the downloaded files to the repository root
          if [ -d "./ar_site/semat.framer.website/ar" ]; then
            rsync -a ./ar_site/semat.framer.website/ar/ ./  # Root directory
          fi
          rm -rf ./ar_site

      - name: Export English Framer Site (Now in /en)
        run: |
          echo "Downloading English site as /en..."
          httrack "https://semat.framer.website/" -O ./en_site --mirror --keep-alive --depth=2 --clean
          mkdir -p ./en
          # Sync the downloaded files to the /en directory
          if [ -d "./en_site/semat.framer.website" ]; then
            rsync -a ./en_site/semat.framer.website/ ./en/
          fi
          rm -rf ./en_site

      - name: Commit and Push Changes
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated update of exported Framer sites (Arabic as main, English as /en)"
            git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git HEAD:main
