name: Export Framer Sites to HTML

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  mirror-and-commit:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2) Install HTTrack & rsync
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y httrack rsync

      # 3) Mirror main site into `main_site`
      - name: Mirror Main Framer Site
        run: |
          echo "Downloading main site..."
          httrack "https://semat.framer.website/" \
            -O ./main_site --mirror --keep-alive --depth=2 --clean

      # 4) Mirror Arabic site into `ar_site`
      - name: Mirror Arabic Framer Site
        run: |
          echo "Downloading Arabic site..."
          httrack "https://semat.framer.website/ar" \
            -O ./ar_site --mirror --keep-alive --depth=2 --clean

      # 5) Combine mirrored content into `site_new`
      - name: Prepare New Content
        run: |
          echo "Preparing new content in site_new..."
          mkdir -p site_new/ar

          # If main site was mirrored
          if [ -d "./main_site/semat.framer.website" ]; then
            rsync -a ./main_site/semat.framer.website/ site_new/
          fi

          # If Arabic site was mirrored
          if [ -d "./ar_site/semat.framer.website/ar" ]; then
            rsync -a ./ar_site/semat.framer.website/ar/ site_new/ar/
          fi

          # Cleanup
          rm -rf main_site ar_site

      # 6) Create/Reset a temporary branch, preserve .git
      - name: Commit to Temporary Branch
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          # Configure Git
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          # Switch to (or create/reset) a branch called mirror-updates
          git checkout -B mirror-updates

          # Remove old site files except .git, .github, site_new
          find . -mindepth 1 -maxdepth 1 \
            ! -name '.git' \
            ! -name '.github' \
            ! -name 'site_new' \
            -exec rm -rf {} +

          # Sync new content from site_new/ into root
          # Exclude .git so it doesn't get removed
          rsync -a --delete \
            --exclude '.git' \
            --exclude '.github' \
            site_new/ ./ || \
            if [ $? -eq 24 ]; then
              echo "Ignoring vanished files (rsync exit code 24)."
            else
              exit $?
            fi

          # Remove the staging folder
          rm -rf site_new

          # Stage & commit if changes
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit on mirror-updates."
            exit 0
          else
            git commit -m "Automated mirror update"
          fi

      # 7) Merge mirror-updates into main, push
      - name: Merge into Main
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          git checkout main
          git pull origin main

          # Merge changes from mirror-updates
          git merge mirror-updates --no-ff -m "Merge mirrored site updates"

          # Push final state
          git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git HEAD:main
